/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop_ui;

import equation_solver.Solutions;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maxwellholloway
 */
public class ChemistryDesktopUITextfile extends javax.swing.JFrame {

    /**
     * Creates new form ChemistryDesktopUITextfile
     */
    public ChemistryDesktopUITextfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textfilePathField = new javax.swing.JTextField();
        balanceFromTextFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        backToMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Textfile Path:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        textfilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfilePathFieldActionPerformed(evt);
            }
        });
        getContentPane().add(textfilePathField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 660, -1));

        balanceFromTextFileButton.setText("Balance!");
        balanceFromTextFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceFromTextFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(balanceFromTextFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        outputBox.setColumns(20);
        outputBox.setRows(5);
        jScrollPane1.setViewportView(outputBox);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 770, 270));

        backToMenuButton.setText("<- Go Back");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfilePathFieldActionPerformed
        // TODO add your handling code here:
        String possiblePath = textfilePathField.getText();
        String solution = new String();
        try {
            solution = Solutions.getTextfileSolutionString(possiblePath);
        } catch (IOException ex) {
            Logger.getLogger(ChemistryDesktopUIManual.class.getName()).log(Level.SEVERE, null, ex);
        }
        outputBox.setText(solution);
    }//GEN-LAST:event_textfilePathFieldActionPerformed

    private void balanceFromTextFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceFromTextFileButtonActionPerformed
        // get the text from the reaction that they input
        String textEntered = textfilePathField.getText();
        String solution = new String();
        try {
            solution = Solutions.getTextfileSolutionString(textEntered);
        } catch (IOException ex) {
            Logger.getLogger(ChemistryDesktopUIManual.class.getName()).log(Level.SEVERE, null, ex);
        }
        outputBox.setText(solution);
    }//GEN-LAST:event_balanceFromTextFileButtonActionPerformed

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        ChemistryDesktopUIMenu.setReturnToMenu(true);
        this.dispose();
    }//GEN-LAST:event_backToMenuButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public void initiateFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mac OS X".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChemistryDesktopUITextfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChemistryDesktopUITextfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChemistryDesktopUITextfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChemistryDesktopUITextfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChemistryDesktopUITextfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JButton balanceFromTextFileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JTextField textfilePathField;
    // End of variables declaration//GEN-END:variables
}
